
title: cp-library
author: sqrtnull
email: sqrtnull@gmail.com
description: >-
  A collection of algorithms and data structures for competitive programming.
baseurl: /cp-library
url: https://sqrtnull.github.io
twitter_username: zelnyok
github_username:  sqrtnull

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  libs:
    output: true